const { withMainApplication } = require('expo/config-plugins')

/**
 * React Native measures text with its own StaticLayout and places inline views
 * (chat math, inline images) from that measurement, but ReactTextView lets the
 * platform TextView draw. OEM text engines can draw differently: vivo OriginOS
 * shrinks the spaces between CJK and Latin text, so lines break elsewhere and
 * a formula lands a character away from its slot. PreparedLayoutTextView draws
 * the measured Layout itself; RN 0.86 enables it only through a feature flag.
 *
 * The generated entry point has already applied the stable flag set, so the
 * flag is forced on top of that same set before any view manager exists.
 * Selectable Text still renders through ReactTextView (the only view with
 * native selection), so paragraphs that hold inline views are not selectable
 * on Android (MarkdownContent).
 */
const MARKER = '// AgentsDock: draw non-selectable Text from its measured layout (generated by withAndroidPreparedTextLayout)'
const LOAD = '    loadReactNative(this)\n'
const LOAD_IMPORT = 'import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative\n'
const IMPORTS = `import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags
import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlagsDefaults
`
const OVERRIDE = `    ${MARKER}
    // The override below is the stable set plus one flag; another release level would silently lose its flags.
    check(DefaultNewArchitectureEntryPoint.releaseLevel == ReleaseLevel.STABLE) { "enablePreparedTextLayout assumes the stable React Native release level" }
    ReactNativeFeatureFlags.dangerouslyForceOverride(object : ReactNativeNewArchitectureFeatureFlagsDefaults() {
      override fun enablePreparedTextLayout(): Boolean = true
    })
`

function applyAndroidPreparedTextLayout(contents) {
  if (contents.includes(MARKER)) return contents
  if (!contents.includes(LOAD) || !contents.includes(LOAD_IMPORT)) {
    throw new Error('Unable to find loadReactNative(this) in Expo\'s generated MainApplication')
  }
  return contents.replace(LOAD_IMPORT, `${LOAD_IMPORT}${IMPORTS}`).replace(LOAD, `${LOAD}${OVERRIDE}`)
}

module.exports = function withAndroidPreparedTextLayout(config) {
  return withMainApplication(config, next => {
    if (next.modResults.language !== 'kt') {
      throw new Error('AgentsDock prepared text layout requires a Kotlin MainApplication')
    }
    next.modResults.contents = applyAndroidPreparedTextLayout(next.modResults.contents)
    return next
  })
}

module.exports.applyAndroidPreparedTextLayout = applyAndroidPreparedTextLayout
module.exports.MARKER = MARKER
