allowBuilds:
  esbuild: true
patchedDependencies:
  react-native-draggable-flatlist@4.0.3: patches/react-native-draggable-flatlist@4.0.3.patch
  react-native-keyboard-controller@1.21.9: patches/react-native-keyboard-controller@1.21.9.patch
