import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const read = relativePath => fs.readFileSync(path.resolve(relativePath), 'utf8')
const types = read('src/types.ts')
const api = read('src/api/AgentServerClient.ts')
const capability = read('src/lib/claude-mcp.ts')
const composer = read('src/components/Composer.tsx')
const chat = read('src/components/ChatScreen.tsx')
const shell = read('src/components/AppShell.tsx')
const panel = read('src/components/ClaudeMcpDialog.tsx')

test('mobile uses the versioned, secret-free Claude MCP wire contract', () => {
  assert.match(types, /export interface ClaudeMcpSnapshot[\s\S]*?version: 1/)
  assert.match(types, /generation: string \| null/)
  assert.match(types, /truncated: boolean/)
  assert.match(types, /expected_generation: string/)
  assert.match(types, /'reconnect' \| 'reconnect_all' \| 'enable' \| 'disable'/)
  assert.match(types, /server_name: string \| null/)
  assert.match(types, /status: ClaudeMcpServerStatus/)
  assert.match(types, /scope: 'user' \| 'project' \| 'local' \| 'claudeai' \| 'managed' \| null/)
  assert.doesNotMatch(types.match(/export interface ClaudeMcpServer \{[\s\S]*?\n\}/)?.[0] ?? '', /command|args|env|headers|url|tools:/i)

  assert.match(api, /claudeMcp\(sessionId: string\): Promise<ClaudeMcpSnapshot>/)
  assert.match(api, /get\(`\/api\/sessions\/\$\{encodeURIComponent\(sessionId\)\}\/claude\/mcp`\)/)
  assert.match(api, /controlClaudeMcp\(sessionId: string, input: ClaudeMcpControlInput\): Promise<ClaudeMcpSnapshot>/)
  assert.match(api, /post\(`\/api\/sessions\/\$\{encodeURIComponent\(sessionId\)\}\/claude\/mcp`, input\)/)
})

test('capability gate and exact slash command fail closed', () => {
  assert.match(capability, /CLAUDE_MCP_MANAGEMENT_MIN_VERSION = 3/)
  assert.match(capability, /version < CLAUDE_MCP_MANAGEMENT_MIN_VERSION \|\| features\.mcp_management !== true/)
  assert.match(capability, /available: candidate\.available === true/)
  assert.match(capability, /\^\\\/mcp\\s\*\$\/i\.test\(text\.trim\(\)\)/)
  assert.match(panel, /MCP management needs a newer AgentsServer/)
  assert.match(panel, /does not advertise Claude MCP management/)
  assert.match(panel, /!connectionReady\n      \|\| !endpointAvailable[\s\S]*?\) return null[\s\S]*?expectedConnection\.claudeMcp\(expectedSessionId\)/)
})

test('exact /mcp opens the app panel without admitting or sending a turn', () => {
  const commandBranch = composer.indexOf('if (consumeComposer && isClaudeMcpCommand(currentDraft))')
  const admission = composer.indexOf('beginTurnAdmission(sessionId)')
  const sendPrompt = composer.indexOf('const request = sendPrompt(')
  assert.ok(commandBranch >= 0)
  assert.ok(commandBranch < admission)
  assert.ok(commandBranch < sendPrompt)
  assert.match(composer, /isClaudeMcpCommand\(currentDraft\)[\s\S]*?currentState\.sessions\.find\(candidate => candidate\.id === sessionId\)[\s\S]*?setSessionDraft\(sessionId, '', profileGeneration\)[\s\S]*?inputRef\.current\?\.clear\(\)[\s\S]*?currentSession\?\.backend === 'claude'\) onOpenMcp\(\)[\s\S]*?return/)
  assert.match(composer, /\/mcp is available in Claude chats only\./)
  assert.match(composer, /mcpCommand \? mcpCommandLabel/)
  assert.match(chat, /<Composer[\s\S]*?onOpenMcp=\{onOpenMcp\}/)
  assert.match(shell, /<ClaudeMcpDialog/)
  assert.match(shell, /mcpSessionId === selected\?\.id/)
})

test('panel fences every result to the active client, profile generation, and selected Claude chat', () => {
  assert.match(panel, /const request = \+\+requestEpoch\.current/g)
  assert.match(panel, /request === requestEpoch\.current/)
  assert.match(panel, /scopeKeyRef\.current === expectedScopeKey/)
  assert.match(panel, /capturedConnectionIsCurrent\(connection, profileId, profileGeneration\)/)
  assert.match(panel, /state\.selectedSessionId === sessionId/)
  assert.match(panel, /session\?\.backend === 'claude'/)
  assert.match(panel, /mounted\.current = false[\s\S]*?requestEpoch\.current \+= 1/)
  assert.match(shell, /setMcpSessionId\(null\)[\s\S]*?setModalGeneration\(profileGeneration\)/)
})

test('controls echo opaque generation, serialize mutations, and stop during active turns', () => {
  assert.match(panel, /expectedMcpGeneration = current\.generation as string/)
  assert.match(panel, /expected_generation: expectedMcpGeneration/)
  assert.match(panel, /busyServer/)
  assert.match(panel, /activeSessionIds\.has\(sessionId\)/)
  assert.match(panel, /turnActive[\s\S]*?MCP status and controls pause while this Claude turn is active/)
  assert.match(panel, /code === 'claude_mcp_generation_changed'/)
  assert.match(panel, /code === 'claude_mcp_server_not_found'/)
  assert.match(panel, /void load\(true\)/)
  assert.match(panel, /more MCP servers than can be shown here/)
  assert.match(panel, /snapshot\.truncated \? 'No displayable MCP servers' : 'No MCP servers configured'/)
  assert.match(panel, /Use Claude Code on the AgentsServer host to view the complete list/)
  assert.match(panel, /mutate\('reconnect_all', null\)/)
  assert.match(panel, /onEnabledChange=\{enabled => void mutate\(enabled \? 'enable' : 'disable', server\.name\)\}/)
  assert.match(panel, /onReconnect=\{\(\) => void mutate\('reconnect', server\.name\)\}/)
  assert.match(panel, /effectiveStatus = server\.enabled \? server\.status : 'disabled'/)
  assert.match(panel, /reconnectDisabled = controlsDisabled \|\| !server\.enabled \|\| server\.status === 'pending'/)
  assert.match(panel, /cause instanceof ServerError[\s\S]*?return fallback/)
  assert.doesNotMatch(panel, /cause\.message/)
})

test('panel exposes accessible status, errors, authentication guidance, and 44pt actions', () => {
  assert.match(panel, /accessibilityViewIsModal/)
  assert.match(panel, /onAccessibilityEscape=\{close\}/)
  assert.match(panel, /accessibilityLiveRegion="polite"/)
  assert.match(panel, /accessibilityRole="alert"/)
  assert.match(panel, /<Switch/)
  assert.match(panel, /For the current Claude session/)
  assert.match(panel, /Changes to enabled servers last only while this Claude session remains loaded/)
  assert.match(panel, /while the current Claude session for this chat remains loaded/)
  assert.match(panel, /Open Claude Code in the AgentsDock terminal and run \/mcp to authenticate this server/)
  assert.match(panel, /headerButton: \{ width: 44, height: 44/)
  assert.match(panel, /reconnect: \{ minWidth: 102, minHeight: 44/)
  assert.match(panel, /stateAction: \{ minWidth: 92, minHeight: 44/)
})
