import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const projection = fs.readFileSync(path.resolve('src/lib/timeline.ts'), 'utf8')
const rows = fs.readFileSync(path.resolve('src/components/TimelineRows.tsx'), 'utf8')
const cards = fs.readFileSync(path.resolve('src/components/CrossChatTimelineCards.tsx'), 'utf8')
const markdown = fs.readFileSync(path.resolve('src/components/MarkdownContent.tsx'), 'utf8')
const inlineReferences = fs.readFileSync(path.resolve('src/lib/timeline-inline-references.ts'), 'utf8')
const types = fs.readFileSync(path.resolve('src/types.ts'), 'utf8')
const memory = fs.readFileSync(path.resolve('src/lib/timeline-memory.ts'), 'utf8')
const rowReuse = fs.readFileSync(path.resolve('src/lib/timeline-row-reuse.ts'), 'utf8')

test('cross-chat lifecycle projection is semantic and internal delivery cannot impersonate a user', () => {
  assert.match(projection, /export function crossChatSemanticKey/)
  assert.match(projection, /cross-chat-exchange:\$\{exchangeId\}/)
  assert.match(projection, /cross-chat:handoff:\$\{handoffId\}/)
  assert.match(projection, /cross-chat:watch:\$\{watchId\}/)
  assert.match(projection, /crossChatTerminalStatusByExchange/)
  assert.match(projection, /crossChatRowsByExchange\.get\(exchangeId\)/)
  assert.match(projection, /event\.purpose === 'cross_chat_handoff_delivery'/)
  assert.match(projection, /const hasVisibleUserContent = Boolean\(messageText\(event\)\.trim\(\) \|\| event\.file_ids\?\.length\)/)
  assert.match(projection, /if \(!isInternalDeliveryTurn\(event\) && hasVisibleUserContent\) active\.user = event/)
  assert.match(projection, /event\.type === 'cross_chat_exchange_failed'/)
  assert.doesNotMatch(projection, /event\.type\.endsWith\('_failed'\)/)
  assert.match(projection, /terminalNormalizedCrossChatEvents/)
  assert.match(projection, /crossChatEventWithStatus\(event, terminalStatus\)/)
  assert.match(projection, /events: \[effectiveEvent\]/)
  assert.match(rows, /events=\{row\.events\}/)
  assert.match(rowReuse, /&& left\.event === right\.event/)
  assert.doesNotMatch(rowReuse, /left\.key\.startsWith\('cross-chat'\).*sameSerializableRecord/s)
})

test('cross-chat cards lazy-load and cancel through scope-fenced server calls', () => {
  assert.match(rows, /<CrossChatHandoffCard/)
  assert.match(rows, /<CrossChatExchangeCard/)
  assert.match(cards, /scope\.connection\.crossChatHandoff\(envelopeId\)/)
  assert.match(cards, /scope\.connection\.cancelCrossChatHandoff\(envelopeId\)/)
  assert.match(cards, /scope\.connection\.crossChatExchange\(exchangeId\)/)
  assert.match(cards, /scope\.connection\.cancelCrossChatExchange\(exchangeId\)/)
  assert.match(cards, /scope\.connection\.skipQueuedCrossChatDelivery\(sessionId, queuedId/)
  assert.match(cards, /client === scope\.connection/)
  assert.match(cards, /scope\.connection\.validationRevision === scope\.validationRevision/)
  assert.match(cards, /state\.activeProfileId === scope\.profileId/)
  assert.match(cards, /state\.profileGeneration === scope\.profileGeneration/)
  assert.match(cards, /state\.selectedSessionId === scope\.sessionId/)
  assert.match(cards, /key=\{`\$\{profileGeneration\}:\$\{props\.sessionId\}:\$\{props\.rowKey\}`\}/)
  assert.match(cards, /loaded\.source_session_id !== sessionId && loaded\.target_session_id !== sessionId/)
  assert.match(cards, /exchangeParticipant\(exchange, sessionId\)/)
  assert.match(cards, /Agent conversation/)
  assert.match(cards, /Show \$\{hiddenLegs\.length\} earlier/)
  assert.match(cards, /exchangeSnapshot\?\.eventSeq === event\.seq/)
  assert.match(cards, /const lastDetailRequestSeq = useRef<number \| null>\(null\)/)
  assert.match(cards, /lastDetailRequestSeq\.current = event\.seq/)
  assert.match(cards, /lastDetailRequestSeq\.current === event\.seq/)
  assert.match(cards, /\[event\.seq, exchangeId, loading, cancelling, open, snapshotCurrent, workspaceRevision\]/)
  assert.match(cards, /label="Retry loading"/)
  assert.match(cards, /Remove queued message/)
  assert.match(cards, /End conversation/)
})

test('exchange conversations use the Zed conversation surface', () => {
  const exchangeCard = cards.slice(
    cards.indexOf('function CrossChatExchangeCardScoped'),
    cards.indexOf('function validateExchange'),
  )
  const handoffCard = cards.slice(
    cards.indexOf('function CrossChatHandoffCardScoped'),
    cards.indexOf('export function CrossChatExchangeCard'),
  )
  assert.match(exchangeCard, /styles\.conversationCard,\s*\{ borderColor: colors\.border, backgroundColor: colors\.raised \}/)
  assert.match(exchangeCard, /styles\.conversationAccent, \{ backgroundColor: colors\.blue \}/)
  assert.doesNotMatch(cards, /CROSS_CHAT_CONVERSATION|useColorScheme|<LinearGradient/)
  assert.match(exchangeCard, /styles\.conversationAccent/)
  assert.match(exchangeCard, /styles\.conversationCard/)
  assert.doesNotMatch(exchangeCard, /styles\.card/)
  assert.match(handoffCard, /styles\.card/)
  assert.match(handoffCard, /colors\.blue/)
  assert.match(cards, /conversationAccent: \{[^}]*width: 3/)
})

test('conversation is visible, semantically aligned, and fully operable', () => {
  assert.match(cards, /label=\{open \? 'Show less' : 'Show full conversation'\}/)
  assert.match(cards, /const allConversationLegsVisible = showEarlier \|\| open/)
  assert.match(cards, /interface CrossChatConversationLeg extends CrossChatExchangeLeg/)
  assert.match(cards, /bodyTruncated: latestExchangeBoolean\(ordered, candidate => candidate\.handoff_body_truncated\) === true/)
  assert.match(cards, /if \(leg\.bodyTruncated\) return true/)
  assert.match(cards, /bodyTruncated: false/)
  assert.match(cards, /requesterSide \? styles\.conversationLegRequester : styles\.conversationLegResponder/)
  assert.match(cards, /conversationLeg: \{ width: '80%'/)
  assert.match(cards, /current \? <View accessibilityElementsHidden style=\{\[styles\.conversationCurrentDot/)
  assert.match(cards, /Waiting for the first agent message\./)
  assert.match(cards, /Could not load the full conversation/)
  assert.match(cards, /testID=\{`cross-chat-details-\$\{exchangeId\}`\}/)
  assert.match(cards, /Stops future messages; work already in progress may still finish\./)
  assert.match(cards, /conversationControl: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /conversationBodyToggle: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /conversationDetailsToggle: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /conversationAction: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /accessibilityLiveRegion="polite"[\s\S]*Queued message removed\./)
  assert.match(cards, /style=\{styles\.conversationLegHeader\}/)
  assert.doesNotMatch(cards, /function ExchangeLegBody/)
  assert.doesNotMatch(cards, /statePill/)
})

test('mobile cross-chat detail stays bounded and dead target navigation reports inline', () => {
  assert.match(cards, /const CROSS_CHAT_BODY_CHUNK = 4_000/)
  assert.match(cards, /text\.slice\(0, limit\)/)
  assert.match(cards, /characters hidden · Show more/)
  assert.match(cards, /The referenced chat is not available in this server workspace/)
  assert.match(cards, /Could not open referenced chat/)
  assert.match(cards, /const counterpartAvailable = Boolean\(counterpart && !counterpart\.archived\)/)
  assert.match(cards, /const counterpartAvailable = sessions\.some\(candidate => candidate\.id === counterpartId && !candidate\.archived\)/)
  assert.match(cards, /counterpartId && counterpartAvailable \? <CardAction/)
  assert.match(cards, /counterpartId && counterpartAvailable \? <ConversationAction/)
  assert.match(cards, /sessions\.find\(candidate => candidate\.id === id\)\?\.title/)
  assert.match(cards, /useAppStore\(state => state\.sessions\)/)
  assert.match(cards, /const errorText = exchange\?\.error \|\| conversationLegs\.find/)
  assert.match(memory, /handoff_preview: truncateText\(event\.handoff_preview, MESSAGE_FIELD_LIMIT\)/)
  assert.match(memory, /source_title: truncateText\(event\.source_title, TIMELINE_LABEL_LIMIT\)/)
  assert.match(memory, /event\.digest, event\.handoff_preview,[\s\S]*event\.output/)
})

test('timeline route history preserves exact local markers and makes remote or hidden routes inert', () => {
  assert.match(inlineReferences, /const legacy = reference\.action === 'route' \? `@@\$\{reference\.display_title_snapshot\}` : null/)
  assert.match(inlineReferences, /const displayText = text\.slice\(reference\.source_text_start, reference\.source_text_end\)/)
  assert.match(inlineReferences, /reference\.target_kind === 'secure_peer' && reference\.action === 'instruction'/)
  assert.match(rows, /timelineInlineReferencesForText\(visible, inlineRoutes\.references, sessionId\)/)
  assert.match(rows, /\.\.\.inlineRoutes\.fallbackReferences/)
  assert.match(rows, /readOnlyReferenceKeys=\{readOnlyReferenceKeys\}/)
  assert.match(rows, /if \(timelineChatReferenceIsRemote\(reference\)\) return/)
  assert.match(markdown, /const interactive = !insideLink[\s\S]*inlineRouteReferenceIsInteractive\(segment\.reference\)/)
  assert.match(markdown, /accessibilityRole=\{interactive \? 'link' : undefined\}/)
  assert.match(markdown, /onPress=\{interactive \? \(\) => onChatReferencePress\?\.\(segment\.reference!\) : undefined\}/)
  assert.match(cards, /const readOnly = remote \|\| readOnlyReferenceKeys\.has\(key\)/)
  assert.match(cards, /if \(readOnly\) return <View[\s\S]*accessibilityRole="text"/)
  assert.match(markdown, /UITextView as SelectableText/)
  assert.match(markdown, /splitInlineRouteMarkerText\(node\.content, prepared\.markers\)/)
})

test('instruction exchanges retain their meaning in the unified conversation details', () => {
  assert.match(types, /export type AgentCrossChatRouteAction = 'instruction' \| 'request_reply'/)
  assert.match(types, /initial_action\?: AgentCrossChatRouteAction \| null/)
  assert.match(types, /exchange_initial_action\?: AgentCrossChatRouteAction \| null/)
  assert.match(cards, /candidate => candidate\.exchange_initial_action/)
  assert.match(cards, /label="Started as" value=\{initialAction === 'instruction' \? 'Instruction' : 'Question with replies'\}/)
  assert.match(cards, /const title = counterpartId \? `Conversation with \$\{counterpartTitle\}` : 'Agent conversation'/)
  assert.match(cards, /requesterTitle\}\{requesterId === sessionId \? ' \(this chat\)' : ''\}/)
  assert.match(cards, /accessibilityLabel=\{`Conversation status: \$\{stateLabel\}`\}/)
  assert.match(cards, /accessibilityState=\{typeof expanded === 'boolean' \? \{ expanded \} : undefined\}/)
  assert.match(types, /exchange_authorization_kind\?: 'explicit_prompt' \| 'configured_route' \| null/)
})
