import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const target = resolve(root, 'src/components/mermaidAssets.ts')
const check = process.argv.includes('--check')

const { version } = JSON.parse(await readFile(resolve(root, 'node_modules/mermaid/package.json'), 'utf8'))
const library = (await readFile(resolve(root, 'node_modules/mermaid/dist/mermaid.min.js'), 'utf8')).replace(/\/\/# sourceMappingURL=.*$/gm, '')
// The library is inlined verbatim into one <script>; a closing tag inside it would end the script early and load a broken page.
if (/<\/script/i.test(library)) throw new Error('mermaid.min.js contains "</script"; the inline embedding needs escaping before it can ship.')

// Host protocol: the app posts {type:'render', source, theme}; the page answers
// {type:'ready'} once it can accept requests, then {type:'rendered', height} or
// {type:'error', message} per request. Only the newest request may answer.
const boot = `(function () {
  var host = document.getElementById('diagram');
  var sequence = 0;
  function post(message) { if (window.ReactNativeWebView) window.ReactNativeWebView.postMessage(JSON.stringify(message)); }
  function height() { var svg = host.firstElementChild; return svg ? Math.ceil(svg.getBoundingClientRect().height) : 0; }
  function receive(event) {
    var request;
    try { request = JSON.parse(event.data); } catch (error) { return; }
    if (!request || request.type !== 'render') return;
    var id = ++sequence;
    mermaid.initialize({ startOnLoad: false, securityLevel: 'strict', suppressErrorRendering: true, theme: request.theme });
    mermaid.render('mermaid-' + id, request.source).then(function (result) {
      if (id !== sequence) return;
      host.innerHTML = result.svg;
      post({ type: 'rendered', height: height() });
    }, function (error) {
      if (id !== sequence) return;
      host.innerHTML = '';
      post({ type: 'error', message: String(error && error.message || error) });
    });
  }
  window.addEventListener('message', receive);
  document.addEventListener('message', receive);
  window.addEventListener('resize', function () { if (host.firstElementChild) post({ type: 'rendered', height: height() }); });
  post({ type: 'ready' });
})();`
const script = `${library}\n${boot}`
const scriptHash = createHash('sha256').update(script).digest()
const csp = [
  "default-src 'none'",
  `script-src 'sha256-${scriptHash.toString('base64')}'`,
  "style-src 'unsafe-inline'",
  "connect-src 'none'",
  "img-src 'none'",
  "media-src 'none'",
  "font-src 'none'",
  "object-src 'none'",
  "frame-src 'none'",
  "worker-src 'none'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ')
const html = [
  '<!doctype html>',
  '<html>',
  '<head>',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">',
  `<meta http-equiv="Content-Security-Policy" content="${csp}">`,
  '<style>html,body{margin:0;padding:0;background:transparent;overflow:hidden}#diagram{display:flex;justify-content:center}#diagram svg{max-width:100%;height:auto}</style>',
  '</head>',
  '<body>',
  '<div id="diagram"></div>',
  `<script>${script}</script>`,
  '</body>',
  '</html>',
].join('')
const generated = [
  '// Generated by scripts/embed-mermaid.mjs. Do not edit by hand.',
  `export const MERMAID_VERSION = ${JSON.stringify(version)}`,
  `export const MERMAID_ASSET_SHA256 = ${JSON.stringify(scriptHash.toString('hex'))}`,
  `export const MERMAID_HTML = ${JSON.stringify(html)}`,
  '',
].join('\n')

const existing = await readFile(target, 'utf8').catch(() => null)
if (check) {
  if (existing !== generated) {
    console.error('Generated mermaid assets are stale. Run: node scripts/embed-mermaid.mjs')
    process.exitCode = 1
  }
} else if (existing !== generated) {
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, generated)
}
